apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: pg-data-pokesky
  name: pg-data-pokesky
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
